### ISSUE TITLE
Possible to add Plex support

### ISSUE THREAD

**Issue by thekiefs** [memen45/SubMusic#33] opened 2021-10-16 19:07 UTC
Hi - is supporting Plex Media Server on the roadmap?

**Comment by thekiefs** [comment] 2021-10-16 19:30
Yes, you're right. There is not an official API, but there is a well maintained python bindings that match the capabilities of the old officially supported API. Check it out: https://github.com/pkkid/python-plexapi

**Comment by memen45** [comment] 2021-10-16 19:34
It seems to be XML responses, do you know if there is a JSON version of the API? The Garmin SDK does not support XML.

**Comment by APIUM** [comment] 2021-11-04 23:36
@thekiefs in the comments for that issue there is this line:

> Or you can use the ElementTree.tostring(obj._data, encoding='utf8', method='xml') to get a xml string then use xmltodict to get a dict then use json dumps

It that what we need? I'm not familiar with the Garmin API.

**Comment by bfalala** [comment] 2022-07-17 21:34
Hi,
It does seem that Plex API supports JSON responses (at least partially). Some documentation can be found here: https://github.com/Arcanemagus/plex-api/wiki/Plex-Web-API-Overview
I too would be interested if Plex was supported :)

**Comment by memen45** [comment] 2022-07-24 10:06
Thanks for your comment! It seems like the complete API can be retrieved in JSON by adding the header `Accept: application/json` to the request, so that is very promising. Without documentation, however, it is very difficult to find out everything needed for SubMusic.

- [ ] how to obtain the `X-Plex-Token` parameter given username and password?
- [ ] how to obtain the required data? Below you can find the current features that are supported by SubMusic that require communication with the backend server. 

| provider method  	| plex api 	| description                                                  	| Content-Type     	|
|------------------	|----------	|--------------------------------------------------------------	|------------------	|
| ping             	| `/identity` 	| returns an object with server version                        	| application/json 	|
| recordPlay       	|          	| submit a play                                                	| application/json 	|
| getAllPlaylists  	|          	| returns array of all playlists available for the user        	| application/json 	|
| getPlaylist      	|          	| returns an array of one playlist object with {id}            	| application/json 	|
| getPlaylistSongs 	|          	| returns an array of songs on the playlist with id            	| application/json 	|
| getRefId         	|          	| returns a refId for a song by {id} (this downloads the song) 	| audio/*          	|
| getArtwork       	|          	| returns a BitmapResource for a song id                       	| image/*          	|
| getAllPodcasts   	|          	| returns array of all podcasts available for the user         	| application/json 	|
| getPodcast       	|          	| returns an array of one podcast object with {id}             	| application/json 	|
| getEpisodes      	|          	| returns array of episodes for podcast with {id}              	| application/json 	|

- [ ] How to handle remote functionality? Option1: ignore the Server Address setting and always login through the common server. Option 2: first try the Server Address, on error, retry login through the common server.

If anyone has experience with the API, or has access to more docs, please let me know!

**Comment by memen45** [comment] 2022-07-24 11:20
Most of the tasks can be done, I verified against a local server install and to complete the table:

| provider method  	| plex api                                                                                 	| description                                                  	| Content-Type     	|
|------------------	|------------------------------------------------------------------------------------------	|--------------------------------------------------------------	|------------------	|
| ping             	| `/identity`                                                                              	| returns an object with server version                        	| application/json 	|
| recordPlay       	| `/:/scrobble?key={songId}&identifier=com.plexapp.plugins.library` (no timestamp support?) 	| submit a play                                                	| application/json 	|
| getAllPlaylists  	| `/playlists?playlistType=audio`                                                          	| returns array of all playlists available for the user        	| application/json 	|
| getPlaylist      	| `/playlists/{id}/items`                                                                  	| returns an array of one playlist object with {id}            	| application/json 	|
| getPlaylistSongs 	| `/playlists/{id}/items`                                                                  	| returns an array of songs on the playlist with {id}          	| application/json 	|
| getRefId         	| `/library/parts/{songId}/{versionid}/file.mp3`                                           	| returns a refId for a song by {id} (this downloads the song) 	| audio/*          	|
| getArtwork       	| `/photo6/:/transcode?url=<pathtoimage>`                                                  	| returns a BitmapResource for a song id                       	| image/*          	|
| getAllPodcasts   	| no support                                                                               	| returns array of all podcasts available for the user         	| application/json 	|
| getPodcast       	| no support                                                                               	| returns an array of one podcast object with {id}             	| application/json 	|
| getEpisodes      	| no support                                                                               	| returns array of episodes for podcast with {id}              	| application/json 	|

So, the podcast feature is not supported as far as I can tell. Also the scrobble option has a limitation, as I could not find out how to send the timestamp along with the scrobble request. Therefore, the scrobble will always be at the time of sync, instead of at the recorded time.

**Comment by memen45** [comment] 2022-07-25 14:13
[Inlog flow](https://forums.plex.tv/t/authenticating-with-plex/609370) is not working anymore. Will use the the authentication token as [obtained by this guide](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/), until another way is discovered. Will edit here as methods are implemented
- [x] ping
- [ ] recordPlay
- [x] getAllPlaylists
- [ ] getPlaylist
- [ ] getPlaylistSongs
- [ ] getRefId
- [ ] getArtwork

**Comment by teejeanely** [comment] 2022-07-26 18:07
> Thanks for your comment! It seems like the complete API can be retrieved in JSON by adding the header `Accept: application/json` to the request, so that is very promising. Without documentation, however, it is very difficult to find out everything needed for SubMusic.
> 
> * [ ]  how to obtain the `X-Plex-Token` parameter given username and password?
> * [ ]  how to obtain the required data? Below you can find the current features that are supported by SubMusic that require communication with the backend server.
> 
> provider method	plex api	description	Content-Type
> ping	`/identity`	returns an object with server version	application/json
> recordPlay		submit a play	application/json
> getAllPlaylists		returns array of all playlists available for the user	application/json
> getPlaylist		returns an array of one playlist object with {id}	application/json
> getPlaylistSongs		returns an array of songs on the playlist with id	application/json
> getRefId		returns a refId for a song by {id} (this downloads the song)	audio/*
> getArtwork		returns a BitmapResource for a song id	image/*
> getAllPodcasts		returns array of all podcasts available for the user	application/json
> getPodcast		returns an array of one podcast object with {id}	application/json
> getEpisodes		returns array of episodes for podcast with {id}	application/json
> * [ ]  How to handle remote functionality? Option1: ignore the Server Address setting and always login through the common server. Option 2: first try the Server Address, on error, retry login through the common server.
> 
> If anyone has experience with the API, or has access to more docs, please let me know!

I've used the X-Plex Token before some home automation.  I've used these instructions to obtain the token for the plex environment.

https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

**Comment by memen45** [comment] 2022-07-27 13:52
Thanks! I found the link as well, it is one post above yours 😃 

Version 0.2.2-eurotas will be published shortly and provides beta support for the Plex API. For the settings, you only need to fill in the API key with the X-Plex-Token [as obtained by this guide (referenced above as well)](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/). The Username is not needed. 

Looking forward to hear your feedback!

**Comment by bfalala** [comment] 2022-07-27 22:02
Thank you for adding Plex !
I can see the playlists and the songs but I can't play or sync anything. When launching a sync, I see "GarminSdkError::0".
Could it be because I use a "Plex direct" URL ? https://[A-B-C-D].[HexString].plex.direct:32400 ?

**Comment by memen45** [comment] 2022-07-27 22:06
Yes, certainly! The problem is with the custom port, this is not supported by the Garmin watches. Is there a way to use the default 80/443 ports?

**Comment by bfalala** [comment] 2022-07-27 22:13
Ok, I will try to change that when I have some time and I'll come back to give you some feedback. Thanks for your quick reply by the way 🙂

**Comment by teejeanely** [comment] 2022-07-27 22:18
Bingo – I got a good connection and can see the playlists! Will continue to test.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by teejeanely** [comment] 2022-07-28 05:03
Some more beta for you. Connected successfully when modifying the port.  Works great

Trying to sync media (playlist to watch via wifi)

Going into more… sync it find the network and the. Waist about 2 min then errors.
[image0.jpeg][image1.jpeg][image2.jpeg]

Tom Giannelli | husband, dad, legend
604.349.6463

On Jul 27, 2022, at 15:13, bfalala ***@***.***> wrote:

﻿

Ok, I will try to change that when I have some time and I'll come back to give you some feedback. Thanks for your quick reply by the way 🙂

**Comment by thekiefs** [comment] 2022-07-29 03:45
Can you explain the exact URL you used?

**Comment by thekiefs** [comment] 2022-07-29 03:45
Can you show the exact URL you used?

**Comment by bfalala** [comment] 2022-07-29 06:43
I managed to make it work 😃
I changed the remote port in Plex to 443 and opened it on my router. Now SubMusic can sync my playlists, music plays flawlessly and song info is properly displayed. Nice work 👍
For information, the URL I use now is like https://[A-B-C-D].[HexString].plex.direct

**Comment by teejeanely** [comment] 2022-07-29 13:49
@bfalala 

I found the same link in the network section of Dev Tools... I too switched to 443 as the public IP for my PMS.  but I'm not having any joy...

- changed pot t 443 and opened the router
- addess URL from network tab to Settings
- no joy :(  i'm getting GarminSdkError:202 Error HTTP --> GarminSDKError::INVALID_HTTP_METHOD_IN_REQUEST as a message.

When I try with just http://xxx.xxx.xxx.xxx:80 I can see playlists etc... when I try and sync the playlists I get an error... I'm working on converting files to MP3 as I ahve all FLAC in the library

**Comment by thekiefs** [comment] 2022-07-29 13:57
> 



> 443

Hmm, I'm running plex in a docker container and it's hard to change this.  @memen45 - is it at all possible to use the default ports?

**Comment by teejeanely** [comment] 2022-07-29 14:01
@thekiefs -- good point.  I'm using plex in a docker container too.  I was changing ports in the plex ui 

I haven't tried changing the host mode... will look at that and see if it breaks any of my setup...

**Comment by memen45** [comment] 2022-07-31 06:57
> @memen45 - is it at all possible to use the default ports?

Garmin SDK does not support custom ports in the url. I have no idea why, and I cannot change it unfortunately. This issue is the same with Subsonic, where the default port is 4040. 

One simple solution might be to setup a very simple proxy. You can leave the docker and Plex settings as is, then setup an Apache server in the same network or even same PC. The way I would do it:
Set up 2 sites/vhosts. The first on port 80, let it redirect to https (port 443). The second on port 443, for this one, you can set up a proxy pass to the Plex server IP + custom port. Now run the let's encrypt certbot to automatically install the certificates on the proxy server. 

If you need, I can look up my own proxy server's vhost and share it!

**Comment by teejeanely** [comment] 2022-07-31 13:48
I would great appreciate you sharing the config example.

Tom

On Jul 30, 2022, at 23:57, memen45 ***@***.***> wrote:

﻿

@memen45<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmemen45&data=05%7C01%7C%7C8cabc880eb974c74baf708da72c1eb1b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637948474447628122%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ciFLJNrAaHxSgLznCBW4P6X%2FJPOBkSEijBXAooPfpkQ%3D&reserved=0> - is it at all possible to use the default ports?

Garmin SDK does not support custom ports in the url. I have no idea why, and I cannot change it unfortunately. This issue is the same with Subsonic, where the default port is 4040.

One simple solution might be to setup a very simple proxy. You can leave the docker and Plex settings as is, then setup an Apache server in the same network or even same PC. The way I would do it:
Set up 2 sites/vhosts. The first on port 80, let it redirect to https (port 443). The second on port 443, for this one, you can set up a proxy pass to the Plex server IP + custom port. Now run the let's encrypt certbot to automatically install the certificates on the proxy server.

If you need, I can look up my own proxy server's vhost and share it!

**Comment by bam2000** [comment] 2022-07-31 16:58
Hi, I have tried today also the pex sync feature. So I used a reverse proxy to get plex to respond to port 443 and I could see and check the playlists I want to sync, when I click on sync it starts syncing but it is kinda stuck at 0% now almost 10 min in syncing and still 0%, I have selected only one Playlist with 18 songs. What can I do to get the sync working ? Thanks

**Comment by memen45** [comment] 2022-08-01 09:10
On the proxy you need a Document Root in order to complete the acme challenge. The ProxyPass will proxy all requests to the given ip address and port, except for the `/.well-known`, as acme challenges cannot be proxied. Then, the rewriting makes sure all traffic is redirected to the https variant, but I think the rewriting is added when you let certbot install certificates for the plexproxy site.

```
<VirtualHost *:80>
    ProxyPreserveHost On

    DocumentRoot "/var/www/plexproxy"

    ProxyPass /.well-known !
    ProxyPass / http://<ip-address>:<port>/
    ProxyPassReverse / http://<ip-address>:<port>/

    ServerName plexproxy.mydomain.nl

RewriteEngine on
RewriteCond %{SERVER_NAME} =plexproxy.mydomain.nl
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

For the 443, the file is almost the same(minus the rewrite rule), and IIRC certbot will automatically create it for you. Hope this helps!

@bam2000: 
1) Indeed, flac is not supported by Garmin as far as I know. I could not find a transcoding option in the plex api yet.
2) The limit of ~25 songs does not apply to Plex. The songs on a playlist can be retrieved in parts through the API, so the Network Response size will be small. The next limit will be available working memory, which is much higher.

**Comment by thekiefs** [comment] 2022-09-03 19:10
@memen45 

1. I found some documentation [here](https://forums.plex.tv/t/music-transcoding-api/696895) on using transcoding for music in the Plex API. I think this should work?

**Comment by memen45** [comment] 2022-09-07 10:13
Thanks @thekiefs , I created a new issue for adding transcoding #56 

Will close this one, as initial plex support seems to be completed now

**Closed** 2022-09-07 10:13 UTC
Labels: enhancement, needs info
