### ISSUE TITLE
Error Code Syncing Plex from Server on ReadyNAS

### ISSUE THREAD

**Issue by cvernon0** [memen45/SubMusic#58] opened 2022-09-27 15:36 UTC
Hi there,  Thanks for developing this app.

I'm having a bit of trouble with it.  I'm not able to log in or sync from my Plex server that's hosted on a NAS device running Linux.

I'm getting error 300 or error 400.

- Plex set up for that NAS server is:  Public Port 443, Private Port 32400 (I have another Plex server on my LAN that is Public 32400, Private 32400 - is that a potential issue? - Plex won't allow the private server to be any other port than 32400)
- NAS is on a static IP:  //192.168.1.XXX
- Router has Port 443 forwarded to 192.168.1.XXX

SubMusic set up address= https://192.168.1.XXX:443

Username is my Plex username.

API Key I obtained from the View XML on "Get Info" in the plex app.  Double and triple-checked the key to make sure it's correct for that server.

Authentication method=API

Enable Skip=on

Is there anything I'm missing in my set up here?  Not sure how to get logs, but I can provide if you can let me know how.

Many thanks

**Comment by memen45** [comment] 2022-09-27 16:11
Thanks for your feedback! I see several potential causes why it is not working:
- The url in the server address cannot contain a custom port, so the `:443` should be stripped. You can choose between port 80/443 by having `http` vs `https` in the url.
- port 443 should be set up with proper HTTPS certificates and TLS 
- if your router has port-forward for port 443, then your server address url should point to the router, not the Plex device. 

I would recommend setting up a reverse proxy with https, which proxies to your local Plex ip:port
- port forward 443 and 80 to the local ip of the proxy server
- an example of a reverse proxy with https in Apache can be found in [#33](https://github.com/memen45/SubMusic/issues/33#issuecomment-1200931272)
- you can use Let's Encrypt and certbot to obtain https certificates for the reverse proxy
- now point your watch to the domain name of the reverse proxy, e.g. `plexproxy.domain.com` 

Hope the above helps!

**Comment by cvernon0** [comment] 2022-09-28 13:55
Thanks for the tips, but unfortunately those steps seem pretty far beyond my capabilities.  I have no idea how to do a reverse proxy, is that a command line thing?  Is there a simple way to configure this to work if I'm not concerned about certificates, https, etc?  Use only port 80?

I've deleted Plex from my NAS and am just running it from a computer on my LAN now.  I thought having two Plex servers was complicating things.  The server is at 192.168.1.15, so do I point SubMusic to that LAN IP address or to my modem IP address?  What port should I specify in Plex and do I need to forward that port on my router?  Do I need to specify that port in SubMusic?  Is 32400 not the right port to use?  I'm confused by that because Plex won't allow you to use any other port for the private port, but you can specify any unused port as the public port.

Thanks again

**Comment by thekiefs** [comment] 2022-10-02 21:09
hi @memen45 - thanks for the support. 

I've followed [this guide](https://www.youtube.com/watch?v=h1a4u72o-64) and setup a proxy server on my Unraid Plex server in Docker. Plex responds great in a browser to both https://plex.domain.com, http://plex.domain.com/ whether on the local network or through remote.

However, when I configure either of the URLs in Garmin and try to sync, I get the following error:

GarminSdkError::-2
Error HTTP --> GarminSdkError::BLE_HOST_TIMEOUT

**Comment by memen45** [comment] 2022-10-05 00:03
Thanks for your detailed feedback! Can you confirm that Test Server option is handled by the phone Bluetooth connection? If the phone is not connected, there would be no internet and a timeout/not connected error would be expected.

During sync, however, the watch changes to its own wifi connection. This is where additional requirements come in, depending on the watch. Please refer to #42 also, and most likely it is required to switch to HTTPS with correct ssl ciphers. That would also require a domain name and DNS record of course.

@cvernon0 I am not sure whether https is built-in to Plex? Otherwise, you need a reverse proxy with valid certificates.

@thekiefs If needed, you can always create a test account and send me some temporary login through the 'Contact developer' option on Connect IQ. That way I can debug against your server instance to see if there is another issue.

**Comment by memen45** [comment] 2022-10-13 18:02
Hey @thekiefs, do you still get the same BLE_HOST_TIMEOUT error or were you able to find the cause? I now have the same error, while using Ampache  backend, so I am wondering if this is some larger issue.

**Comment by thekiefs** [comment] 2022-10-16 02:09
Hi @memen45 - I no longer get the BLE_HOST_TIMEOUT error.

When I "Test Server" I receive "Inlog OK".

But, I am still experiencing what @cvernon0 describes. 

Do you want me to send you logs, or - happy to send you a test account

**Comment by memen45** [comment] 2022-10-16 09:41
Yes, both logs and a test account could help a lot!

Without the BLE_HOST_TIMEOUT error, the sync problem might be because the watch requires https certificates. When fetching playlists and 'Test server', the watch connects through the phone. During sync, the watch connects to wifi and the url by itself, and thus may have different requirements.

**Comment by thekiefs** [comment] 2022-10-16 13:34
Great. I couldn't find how to send logs but I sent you info for the test account!

**Comment by memen45** [comment] 2022-10-16 16:07
@cvernon0 I have released a new version: 0.2.5-argalus. I have found a bug where the request limit was not set during sync. This might solve this issue, but I am not 100% certain. Let me know if you still encounter any issues!

**Comment by thekiefs** [comment] 2022-10-17 00:19
Works great for me now!

**Comment by cvernon0** [comment] 2022-10-18 14:16
Works great for me now as well!  Thanks for the support @memen45.

**Comment by memen45** [comment] 2022-10-19 09:16
Thanks for all your feedback! I will close this issue and open two new ones for the standing problems.

**Closed by memen45** 2022-10-19 09:16 UTC

**Comment by thekiefs** [comment] 2022-10-23 15:52
> Without the BLE_HOST_TIMEOUT error, the sync problem might be because the watch requires https certificates. When fetching playlists and 'Test server', the watch connects through the phone. During sync, the watch connects to wifi and the url by itself, and thus may have different requirements.

hey @memen45 - unfortunately I broke my phone and only have access to my watch and computer. While I wait for a new phone, I tried checking available playlists and syncing music. When I try to browse/select playlist and test server from the music settings screen, I get an IQ! screen. I also ran into the BLE error again.

Any way we could have a fallback to wifi in the event bluetooth is unavailable?

**Comment by memen45** [comment] 2022-10-23 18:52
As far as I know, it is not possible to use the wifi connection for everything. Browsing the server requires Bluetooth connection, but you can remove local and synced playlists. The sync should still be working using wifi, though.

Exceptions should not occur while browsing, it should just show 'Nothing to show', I think. I can look into these exceptions tomorrow.
