### ISSUE TITLE
Media Error Occurred

### ISSUE THREAD

**Issue by markcs** [memen45/SubMusic#25] opened 2021-07-30 00:57 UTC
After I sync I often get an error 'Media Error Occurred' when swiping to start the media player (I have a Venu).  After I get this error, I am unable to do anything with SubMusic and I can not even force a resync.

I am using Nextcloud 21.0.3 with the Music app version 1.2.1 using Ampache API.

I checked for the CIQ log file and found the following errors:

```
---
Error: Unhandled Exception
Time: 2021-07-29T11:46:11Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.3
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 45
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x10005f31
  - pc: 0x10005c48
---
Error: Unhandled Exception
Time: 2021-07-29T11:46:14Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.3
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 45
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x10005f31
  - pc: 0x10005c48
```

Let me know if there is more debugging I can do to help to isolate the issue.

**Comment by memen45** [comment] 2021-08-03 22:56
Sorry for the delay, I will check the error logs tomorrow and see if I can find more details. Do you have specific playlists or files that result in the error?

**Comment by memen45** [comment] 2021-08-04 14:58
The currently playing playlist is stored on the watch and loaded when the music widget is loaded. When songs are removed from a playlist, this currently playing list is not updated and therefore potentially lists songs that have been deleted from storage. This is fixed in the next update 0.1.11-lima. Thanks a lot for reporting this issue, really appreciated!

Please let me know if the problem is fixed with the new update!

**Comment by markcs** [comment] 2021-08-05 02:14
This seemed to almost fix the issue.  To test, I re-installed SubMusic, sync'd a playlist successfully and then removed a song from the list.  I am now able to get back into SubMusic, but I did notice this crash the first time I tried to go to the end of the play list.  I could not reproduce it though the next time I tried.

```
---
Error: Invalid Value
Details: 'Failed invoking <symbol>'
Time: 2021-08-05T01:52:32Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.3
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 45
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x100059a5
  - pc: 0x1000588c
  - pc: 0x10006bcd
---
Error: Unhandled Exception
Time: 2021-08-05T01:52:35Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.3
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 45
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x10005f31
  - pc: 0x10005e25
---
Error: Array Out Of Bounds Error
Details: 'Failed invoking <symbol>'
Time: 2021-08-05T01:55:25Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.4
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 46
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x100056fe
  - pc: 0x10006145
  - pc: 0x10006052
---
Error: Array Out Of Bounds Error
Details: 'Failed invoking <symbol>'
Time: 2021-08-05T01:55:30Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.4
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 46
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x100056fe
  - pc: 0x10006145
  - pc: 0x10006052
---
Error: Array Out Of Bounds Error
Details: 'Failed invoking <symbol>'
Time: 2021-08-05T01:55:33Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.4
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 46
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x100056fe
  - pc: 0x10006145
  - pc: 0x10006052
---
Error: Array Out Of Bounds Error
Details: 'Failed invoking <symbol>'
Time: 2021-08-05T01:55:39Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.4
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 46
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x100056fe
  - pc: 0x10006145
  - pc: 0x10006052
---
Error: Array Out Of Bounds Error
Details: 'Failed invoking <symbol>'
Time: 2021-08-05T01:55:57Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.4
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 46
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x100056fe
  - pc: 0x10006145
  - pc: 0x10006052
---
Error: Array Out Of Bounds Error
Details: 'Failed invoking <symbol>'
Time: 2021-08-05T01:56:00Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.4
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 46
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x100056fe
  - pc: 0x10006145
  - pc: 0x10006052
---
Error: Array Out Of Bounds Error
Details: 'Failed invoking <symbol>'
Time: 2021-08-05T01:56:35Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.4
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 46
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x100056fe
  - pc: 0x10006145
  - pc: 0x10006052
---
Error: Array Out Of Bounds Error
Details: 'Failed invoking <symbol>'
Time: 2021-08-05T01:56:38Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.4
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 46
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x100056fe
  - pc: 0x10006145
  - pc: 0x10006052
---
Error: Array Out Of Bounds Error
Details: 'Failed invoking <symbol>'
Time: 2021-08-05T01:57:41Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.4
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 46
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x100056fe
  - pc: 0x10006145
  - pc: 0x10006052
---
Error: Array Out Of Bounds Error
Details: 'Failed invoking <symbol>'
Time: 2021-08-05T01:57:48Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.4
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 46
Filename: B7RC4847
Appname: SubMusic
Stack: 
  - pc: 0x100056fe
  - pc: 0x10006145
  - pc: 0x10006052
---
Error: System Error
Details: Error in onSong()
Time: 2021-08-05T02:06:23Z
Part-Number: 006-B3226-00
Firmware-Version: '6.10'
Language-Code: eng
ConnectIQ-Version: 4.0.4
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 46
Filename: B8520018
Appname: SubMusic
Stack: 
```

**Comment by memen45** [comment] 2021-08-05 12:53
Thanks a lot for testing! I am not sure how the crash could have happened. Unfortunately due to [this Garmin bug](https://forums.garmin.com/developer/connect-iq/i/bug-reports/newly-updated-app-reporting-the-selected-key-does-not-belong-to-appname-please-select-another-key-in-era) I am unable to see any new crash reports since updating the app yesterday. If you continue to have crashes, please let me know. I will look into the crash reports when they are available again.

**Comment by lemieuxl** [comment] 2021-08-24 17:35
I'm having a similar issue.

Using *airsonic* with the *subsonic* API, I've successfully synced two playlists (25 songs each). Then, I updated those two playlists (removing and adding songs in both) and all was fine. Getting to the SubMusic app (Venu 2), I selected the "Play all" option, and the message "*Media Error Occurred*" appeared.

I'm using version 0.1.11-lima of the app, and I don't know how to get any error log.

**Comment by memen45** [comment] 2021-08-25 11:37
Thanks for your report! Found your device in the crash reports. Also found the cause, I was unfortunately indexing the song array while removing from it in the same for loop. Should be fixed with the new update: 0.1.12-mike.

Let me know if it fixes your issue!

**Comment by memen45** [comment] 2021-08-30 12:32
Found some crashes again, so reopened it. With the latest release 0.1.13-november it should finally be fixed (thoroughly tested this time). Thanks again for your feedback!

**Closed by memen45** 2021-08-30 12:32 UTC
Labels: bug, good first issue

**Comment by slytekorg** [comment] 2023-08-21 11:53
hey. I have same crash. Forerunner 945. Ampache. I have crash on Server Settings, Sync, Playlists etc. But sometimes it work and I don't know what to do.

```
Error: Unexpected Type Error
Details: 'Failed invoking <symbol>'
Time: 2023-08-21T11:42:44Z
Part-Number: 006-B3113-00
Firmware-Version: '13.00'
Language-Code: eng
ConnectIQ-Version: 4.2.2
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 77
Filename: D8KG0616
Appname: SubMusic
Stack: 
  - pc: 0x1000cc0d
  - pc: 0x1000cb6e
  - pc: 0x1000dac6
  - pc: 0x1000da69
  - pc: 0x1000b4a0
  - pc: 0x1000b5ee
  - pc: 0x10004028
````
