### ISSUE TITLE
Method to cancel a sync

### ISSUE THREAD

**Issue by thekiefs** [memen45/SubMusic#64] opened 2022-12-27 01:20 UTC
I froze syncing my Plex playlist. Is there a way to cancel a sync and retry? Or do I have to fully reboot the watch?

**Comment by memen45** [comment] 2022-12-27 23:42
Normally, it shouldn't freeze. Any errors are either handled by SubMusic directly without stopping the sync (e.g. response size adjustments) or escalate to skipping certain sync steps, resulting in completion of the sync.

There are crashes possible during the sync, such as timeouts or out of memory errors. These ones are currently not caught in software and could interrupt the sync. Not sure how Garmin handles such interruptions. 

On what device did you see this issue? Maybe I can check the error logs to find the cause.
Either way, rebooting while a sync is in progress should not corrupt storage in most cases, so should be safe. If you tried to sync many playlists at once, you could try to do it in smaller steps at a time. This reduces the chances of a timeout error.

**Comment by thekiefs** [comment] 2022-12-27 23:51
I saw it on a Garmin Descent MK2. There was a funky bug with a lot of the metadata being totally wrong. I rebooted the watch, cleared cache/data, and restarted the sync and it worked this time.

**Comment by memen45** [comment] 2023-01-11 11:46
Closing this, as either it is resolved, or it is in the Garmin software (sync can be cancelled, and hooks for it are implemented and handled correctly by SubMusic already).

**Closed by memen45** 2023-01-11 11:46 UTC
